In [79]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
import seaborn as sns
import numpy as np

In [80]:
df = pd.read_csv('AqSolDB_v1.0_min.csv')

In [81]:
def smiles_to_mol(s):
    try:
        return Chem.MolFromSmiles(str(s))
    except Exception as e:
        return None


df['mol'] = df['SMILES'].astype(str).map(smiles_to_mol)

[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] Explicit valence for atom # 5 N, 4, is greater than permitted
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] Explicit valence for atom # 5 N, 4, is greater than permitted
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors
[02:00:41] WARNING: not removing hydrogen atom without neighbors

In [82]:
df

,ID,Name,InChIKey,SMILES,Solubility,mol
0,A-3,"N,N,N-trimethyloctadecan-1-aminium bromide",SZEMGTQCPRNXEG-UHFFFAOYSA-M,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,<rdkit.Chem.rdchem.Mol object at 0x119b07760>
1,A-4,Benzo[cd]indol-2(1H)-one,GPYLCFQEKPUWLD-UHFFFAOYSA-N,O=C1Nc2cccc3cccc1c23,-3.254767,<rdkit.Chem.rdchem.Mol object at 0x119dd9e00>
2,A-5,4-chlorobenzaldehyde,AVPYQKSLYISFPO-UHFFFAOYSA-N,Clc1ccc(C=O)cc1,-2.177078,<rdkit.Chem.rdchem.Mol object at 0x119dd9e70>
3,A-8,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",XTUPUYCJWKHGSW-UHFFFAOYSA-L,[Zn++].CC(c1ccccc1)c2cc(C(C)c3ccccc3)c(O)c(c2)...,-3.924409,<rdkit.Chem.rdchem.Mol object at 0x119dd9ee0>
4,A-9,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,FAUAZXVRLVIARB-UHFFFAOYSA-N,C1OC1CN(CC2CO2)c3ccc(Cc4ccc(cc4)N(CC5CO5)CC6CO...,-4.662065,<rdkit.Chem.rdchem.Mol object at 0x119dd9f50>
...,...,...,...,...,...,...
9977,I-84,tetracaine,GKCBAIGFKIBETG-UHFFFAOYSA-N,C(c1ccc(cc1)NCCCC)(=O)OCCN(C)C,-3.010000,<rdkit.Chem.rdchem.Mol object at 0x119f9a9d0>
9978,I-85,tetracycline,OFVLGDICTFRJMM-WESIUVDSSA-N,OC1=C(C(C2=C(O)[C@@](C(C(C(N)=O)=C(O)[C@H]3N(C...,-2.930000,<rdkit.Chem.rdchem.Mol object at 0x119f9aa40>
9979,I-86,thymol,MGSRCZKZVOBKFT-UHFFFAOYSA-N,c1(cc(ccc1C(C)C)C)O,-2.190000,<rdkit.Chem.rdchem.Mol object at 0x119f9aab0>
9980,I-93,verapamil,SGTNSNPWRIOYBX-UHFFFAOYSA-N,COc1ccc(CCN(C)CCCC(C#N)(C(C)C)c2ccc(OC)c(OC)c2...,-3.980000,<rdkit.Chem.rdchem.Mol object at 0x119f9ab20>
9981,I-94,warfarin,PJVWKTKQMONHTI-UHFFFAOYSA-N,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,-4.780000,<rdkit.Chem.rdchem.Mol object at 0x119f9ab90>

In [83]:
RADIUS   = 2
N_BITS   = 2 ^ 12
CHIRAL   = True

morganGenerator = rdFingerprintGenerator.GetMorganGenerator(radius=2, fpSize=2^12)
def mol_to_ecfp(mol):
    if mol is None:
        return None
    global morganGenerator
    return morganGenerator.GetFingerprint(mol=mol)

df['ECFP'] = df['mol'].map(mol_to_ecfp)

In [84]:
df

,ID,Name,InChIKey,SMILES,Solubility,mol,ECFP
0,A-3,"N,N,N-trimethyloctadecan-1-aminium bromide",SZEMGTQCPRNXEG-UHFFFAOYSA-M,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,<rdkit.Chem.rdchem.Mol object at 0x119b07760>,"[1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0]"
1,A-4,Benzo[cd]indol-2(1H)-one,GPYLCFQEKPUWLD-UHFFFAOYSA-N,O=C1Nc2cccc3cccc1c23,-3.254767,<rdkit.Chem.rdchem.Mol object at 0x119dd9e00>,"[0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1]"
2,A-5,4-chlorobenzaldehyde,AVPYQKSLYISFPO-UHFFFAOYSA-N,Clc1ccc(C=O)cc1,-2.177078,<rdkit.Chem.rdchem.Mol object at 0x119dd9e70>,"[1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0]"
3,A-8,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",XTUPUYCJWKHGSW-UHFFFAOYSA-L,[Zn++].CC(c1ccccc1)c2cc(C(C)c3ccccc3)c(O)c(c2)...,-3.924409,<rdkit.Chem.rdchem.Mol object at 0x119dd9ee0>,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]"
4,A-9,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,FAUAZXVRLVIARB-UHFFFAOYSA-N,C1OC1CN(CC2CO2)c3ccc(Cc4ccc(cc4)N(CC5CO5)CC6CO...,-4.662065,<rdkit.Chem.rdchem.Mol object at 0x119dd9f50>,"[1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1]"
...,...,...,...,...,...,...,...
9977,I-84,tetracaine,GKCBAIGFKIBETG-UHFFFAOYSA-N,C(c1ccc(cc1)NCCCC)(=O)OCCN(C)C,-3.010000,<rdkit.Chem.rdchem.Mol object at 0x119f9a9d0>,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
9978,I-85,tetracycline,OFVLGDICTFRJMM-WESIUVDSSA-N,OC1=C(C(C2=C(O)[C@@](C(C(C(N)=O)=C(O)[C@H]3N(C...,-2.930000,<rdkit.Chem.rdchem.Mol object at 0x119f9aa40>,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1]"
9979,I-86,thymol,MGSRCZKZVOBKFT-UHFFFAOYSA-N,c1(cc(ccc1C(C)C)C)O,-2.190000,<rdkit.Chem.rdchem.Mol object at 0x119f9aab0>,"[0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1]"
9980,I-93,verapamil,SGTNSNPWRIOYBX-UHFFFAOYSA-N,COc1ccc(CCN(C)CCCC(C#N)(C(C)C)c2ccc(OC)c(OC)c2...,-3.980000,<rdkit.Chem.rdchem.Mol object at 0x119f9ab20>,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"
9981,I-94,warfarin,PJVWKTKQMONHTI-UHFFFAOYSA-N,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,-4.780000,<rdkit.Chem.rdchem.Mol object at 0x119f9ab90>,"[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]"

In [85]:
df = df.dropna(subset=['ECFP', 'Solubility']).copy()

In [86]:
x = np.zeros((len(df), 2^12), dtype=np.int8)
y = df['Solubility'].astype(float).to_numpy()

In [87]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.30, random_state=42
)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
    n_estimators=50000,
    max_depth=None,
)
rf.fit(x_train, y_train)

In [78]:
from sklearn.metrics import r2_score, mean_squared_error

pred = rf.predict(x_test)
r2 = r2_score(y_test, pred)
rmse = mean_squared_error(y_test, pred)

print(f"random forest (n={rf.n_estimators})")
print(f"R^2:  {r2:.3f}")
print(f"RMSE: {rmse:.3f}")

random forest (n=500)
R^2:  -0.000
RMSE: 5.567