In [12]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem import rdFingerprintGenerator
import seaborn as sns
import numpy as np

In [13]:
df = pd.read_csv('AqSolDB_v1.0_min.csv')

In [14]:
def smiles_to_mol(s):
    try:
        return Chem.MolFromSmiles(str(s))
    except Exception as e:
        return None


df['mol'] = df['SMILES'].astype(str).map(smiles_to_mol)

[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] Explicit valence for atom # 5 N, 4, is greater than permitted
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] Explicit valence for atom # 5 N, 4, is greater than permitted
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors
[02:08:37] WARNING: not removing hydrogen atom without neighbors

In [15]:
df

,ID,Name,InChIKey,SMILES,Solubility,mol
0,A-3,"N,N,N-trimethyloctadecan-1-aminium bromide",SZEMGTQCPRNXEG-UHFFFAOYSA-M,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,<rdkit.Chem.rdchem.Mol object at 0x11a12a110>
1,A-4,Benzo[cd]indol-2(1H)-one,GPYLCFQEKPUWLD-UHFFFAOYSA-N,O=C1Nc2cccc3cccc1c23,-3.254767,<rdkit.Chem.rdchem.Mol object at 0x11a12a030>
2,A-5,4-chlorobenzaldehyde,AVPYQKSLYISFPO-UHFFFAOYSA-N,Clc1ccc(C=O)cc1,-2.177078,<rdkit.Chem.rdchem.Mol object at 0x11a12a1f0>
3,A-8,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",XTUPUYCJWKHGSW-UHFFFAOYSA-L,[Zn++].CC(c1ccccc1)c2cc(C(C)c3ccccc3)c(O)c(c2)...,-3.924409,<rdkit.Chem.rdchem.Mol object at 0x11a12a340>
4,A-9,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,FAUAZXVRLVIARB-UHFFFAOYSA-N,C1OC1CN(CC2CO2)c3ccc(Cc4ccc(cc4)N(CC5CO5)CC6CO...,-4.662065,<rdkit.Chem.rdchem.Mol object at 0x11a12a3b0>
...,...,...,...,...,...,...
9977,I-84,tetracaine,GKCBAIGFKIBETG-UHFFFAOYSA-N,C(c1ccc(cc1)NCCCC)(=O)OCCN(C)C,-3.010000,<rdkit.Chem.rdchem.Mol object at 0x11a257060>
9978,I-85,tetracycline,OFVLGDICTFRJMM-WESIUVDSSA-N,OC1=C(C(C2=C(O)[C@@](C(C(C(N)=O)=C(O)[C@H]3N(C...,-2.930000,<rdkit.Chem.rdchem.Mol object at 0x11a2570d0>
9979,I-86,thymol,MGSRCZKZVOBKFT-UHFFFAOYSA-N,c1(cc(ccc1C(C)C)C)O,-2.190000,<rdkit.Chem.rdchem.Mol object at 0x11a257140>
9980,I-93,verapamil,SGTNSNPWRIOYBX-UHFFFAOYSA-N,COc1ccc(CCN(C)CCCC(C#N)(C(C)C)c2ccc(OC)c(OC)c2...,-3.980000,<rdkit.Chem.rdchem.Mol object at 0x11a2571b0>
9981,I-94,warfarin,PJVWKTKQMONHTI-UHFFFAOYSA-N,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,-4.780000,<rdkit.Chem.rdchem.Mol object at 0x11a257220>

In [16]:
RADIUS   = 2
N_BITS   = 2 ^ 12
CHIRAL   = True

morganGenerator = rdFingerprintGenerator.GetMorganGenerator(radius=3, fpSize=2^10)
def mol_to_ecfp(mol):
    if mol is None:
        return None
    global morganGenerator
    return morganGenerator.GetFingerprint(mol=mol)

df['ECFP'] = df['mol'].map(mol_to_ecfp)

In [17]:
df

,ID,Name,InChIKey,SMILES,Solubility,mol,ECFP
0,A-3,"N,N,N-trimethyloctadecan-1-aminium bromide",SZEMGTQCPRNXEG-UHFFFAOYSA-M,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,<rdkit.Chem.rdchem.Mol object at 0x11a12a110>,"[1, 1, 1, 1, 1, 0, 1, 1]"
1,A-4,Benzo[cd]indol-2(1H)-one,GPYLCFQEKPUWLD-UHFFFAOYSA-N,O=C1Nc2cccc3cccc1c23,-3.254767,<rdkit.Chem.rdchem.Mol object at 0x11a12a030>,"[1, 1, 1, 1, 1, 1, 1, 1]"
2,A-5,4-chlorobenzaldehyde,AVPYQKSLYISFPO-UHFFFAOYSA-N,Clc1ccc(C=O)cc1,-2.177078,<rdkit.Chem.rdchem.Mol object at 0x11a12a1f0>,"[1, 1, 1, 1, 1, 0, 1, 1]"
3,A-8,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",XTUPUYCJWKHGSW-UHFFFAOYSA-L,[Zn++].CC(c1ccccc1)c2cc(C(C)c3ccccc3)c(O)c(c2)...,-3.924409,<rdkit.Chem.rdchem.Mol object at 0x11a12a340>,"[1, 1, 1, 1, 1, 1, 1, 1]"
4,A-9,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,FAUAZXVRLVIARB-UHFFFAOYSA-N,C1OC1CN(CC2CO2)c3ccc(Cc4ccc(cc4)N(CC5CO5)CC6CO...,-4.662065,<rdkit.Chem.rdchem.Mol object at 0x11a12a3b0>,"[1, 1, 1, 1, 1, 1, 1, 1]"
...,...,...,...,...,...,...,...
9977,I-84,tetracaine,GKCBAIGFKIBETG-UHFFFAOYSA-N,C(c1ccc(cc1)NCCCC)(=O)OCCN(C)C,-3.010000,<rdkit.Chem.rdchem.Mol object at 0x11a257060>,"[1, 1, 1, 1, 1, 1, 1, 1]"
9978,I-85,tetracycline,OFVLGDICTFRJMM-WESIUVDSSA-N,OC1=C(C(C2=C(O)[C@@](C(C(C(N)=O)=C(O)[C@H]3N(C...,-2.930000,<rdkit.Chem.rdchem.Mol object at 0x11a2570d0>,"[1, 1, 1, 1, 1, 1, 1, 1]"
9979,I-86,thymol,MGSRCZKZVOBKFT-UHFFFAOYSA-N,c1(cc(ccc1C(C)C)C)O,-2.190000,<rdkit.Chem.rdchem.Mol object at 0x11a257140>,"[1, 1, 1, 1, 1, 1, 1, 1]"
9980,I-93,verapamil,SGTNSNPWRIOYBX-UHFFFAOYSA-N,COc1ccc(CCN(C)CCCC(C#N)(C(C)C)c2ccc(OC)c(OC)c2...,-3.980000,<rdkit.Chem.rdchem.Mol object at 0x11a2571b0>,"[1, 1, 1, 1, 1, 1, 1, 1]"
9981,I-94,warfarin,PJVWKTKQMONHTI-UHFFFAOYSA-N,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,-4.780000,<rdkit.Chem.rdchem.Mol object at 0x11a257220>,"[1, 1, 1, 1, 1, 1, 1, 1]"

In [18]:
df = df.dropna(subset=['ECFP', 'Solubility']).copy()

In [19]:
from rdkit import DataStructs
df = df.dropna(subset=['ECFP', 'Solubility']).copy()

x = np.zeros((len(df), 2^2048), dtype=np.int8)
for i, fp in enumerate(df['ECFP']):
    arr = np.zeros((2^2048,), dtype=np.int8)
    print(fp)
    DataStructs.ConvertToNumpyArray(fp, arr)
    x[i] = arr
y = df['Solubility'].astype(float).to_numpy()

In [20]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.30, random_state=42
)

In [21]:
from xgboost import XGBRegressor

xgb = XGBRegressor(
    n_estimators=2000,          # lots of trees, rely on early stopping
    learning_rate=0.03,         # smaller step
    max_depth=8,                # depth for nonlinearity; adjust if overfitting
    subsample=0.8,              # bagging
    colsample_bytree=0.6,       # feature subsampling
    reg_lambda=1.0,             # L2
    reg_alpha=0.0,              # L1
    min_child_weight=1.0,
    random_state=42,
    n_jobs=-1,
    tree_method="hist",         # fast, good default
    eval_metric="rmse"
)

xgb.fit(
    x_train, y_train,
    eval_set=[(x_train, y_train), (x_test, y_test)],
    verbose=False,
)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=0.6, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric='rmse', feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.03, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=8,
             max_leaves=None, min_child_weight=1.0, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=2000,
             n_jobs=-1, num_parallel_tree=None, ...)

In [22]:
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

pred = xgb.predict(x_test)
r2 = r2_score(y_test, pred)
rmse = mean_squared_error(y_test, pred)
mae = mean_absolute_error(y_test, pred)

print(f"xgboost (n={xgb.n_estimators})")
print(f"R^2:  {r2:.3f}")
print(f"RMSE: {rmse:.3f}")

xgboost (n=2000)
R^2:  -0.000
RMSE: 5.567